FROM alpine/git

RUN apk add --no-cache docker-cli

RUN apk add --no-cache bash

COPY monitor.sh /app/monitor.sh

RUN chmod +x /app/monitor.sh

RUN chmod +x /app/monitor.sh

ENTRYPOINT ["/app/monitor.sh"]
